In [13]:
%pip install pandas

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pandas in /Users/abhipsha/Library/Python/3.9/lib/python/site-packages (2.3.3)
Requirement already satisfied: pytz>=2020.1 in /Users/abhipsha/Library/Python/3.9/lib/python/site-packages (from pandas) (2026.2)
Requirement already satisfied: tzdata>=2022.7 in /Users/abhipsha/Library/Python/3.9/lib/python/site-packages (from pandas) (2026.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/abhipsha/Library/Python/3.9/lib/python/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: numpy>=1.22.4 in /Users/abhipsha/Library/Python/3.9/lib/python/site-packages (from pandas) (2.0.2)
Requirement already satisfied: six>=1.5 in /Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/site-packages (from python-dateutil>=2.8.2->pandas) (1.15.0)
WARNING: You are using pip version 21.2.4; however, version 26.0.1 is available.
You should consider upgrading via the '/Library/Developer/CommandLineTools/usr/bin/python3 -m pip install --upgrade pip' command.
Note: you may need to restart the kernel to use updated packages.

In [16]:
import pandas as pd

In [17]:
df = pd.read_csv('customer_shopping_behavior.csv')
df.head()

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,Yes,14,Venmo,Fortnightly
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,Yes,2,Cash,Fortnightly
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,Yes,23,Credit Card,Weekly
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,Yes,49,PayPal,Weekly
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,Yes,31,PayPal,Annually

In [18]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3900 entries, 0 to 3899
Data columns (total 18 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Customer ID             3900 non-null   int64
 1   Age                     3900 non-null   int64
 2   Gender                  3900 non-null   object
 3   Item Purchased          3900 non-null   object
 4   Category                3900 non-null   object
 5   Purchase Amount (USD)   3900 non-null   int64
 6   Location                3900 non-null   object
 7   Size                    3900 non-null   object
 8   Color                   3900 non-null   object
 9   Season                  3900 non-null   object
 10  Review Rating           3863 non-null   float64
 11  Subscription Status     3900 non-null   object
 12  Shipping Type           3900 non-null   object
 13  Discount Applied        3900 non-null   object
 14  Promo Code Used         3900 non-null   object
 15  Previous Purchases      3900 non-null   int64
 16  Payment Method          3900 non-null   object
 17  Frequency of Purchases  3900 non-null   object
dtypes: float64(1), int64(4), object(13)
memory usage: 548.6+ KB

In [19]:
df.describe()

,Customer ID,Age,Purchase Amount (USD),Review Rating,Previous Purchases
count,3900.000000,3900.000000,3900.000000,3863.000000,3900.000000
mean,1950.500000,44.068462,59.764359,3.750065,25.351538
std,1125.977353,15.207589,23.685392,0.716983,14.447125
min,1.000000,18.000000,20.000000,2.500000,1.000000
25%,975.750000,31.000000,39.000000,3.100000,13.000000
50%,1950.500000,44.000000,60.000000,3.800000,25.000000
75%,2925.250000,57.000000,81.000000,4.400000,38.000000
max,3900.000000,70.000000,100.000000,5.000000,50.000000

In [20]:
df.isnull().sum()

Customer ID                0
Age                        0
Gender                     0
Item Purchased             0
Category                   0
Purchase Amount (USD)      0
Location                   0
Size                       0
Color                      0
Season                     0
Review Rating             37
Subscription Status        0
Shipping Type              0
Discount Applied           0
Promo Code Used            0
Previous Purchases         0
Payment Method             0
Frequency of Purchases     0
dtype: int64

In [21]:
df['Review Rating']= df.groupby('Category')['Review Rating'].transform(lambda x: x.fillna(x.median()))

In [22]:
df.isnull().sum()

Customer ID               0
Age                       0
Gender                    0
Item Purchased            0
Category                  0
Purchase Amount (USD)     0
Location                  0
Size                      0
Color                     0
Season                    0
Review Rating             0
Subscription Status       0
Shipping Type             0
Discount Applied          0
Promo Code Used           0
Previous Purchases        0
Payment Method            0
Frequency of Purchases    0
dtype: int64

In [23]:
df.columns = df.columns.str.replace(' ', '_')
df.columns = df.columns.str.lower()
df = df.rename(columns={'purchase_amount_(usd)': 'purchase_amount'})
df.head()

,customer_id,age,gender,item_purchased,category,purchase_amount,location,size,color,season,review_rating,subscription_status,shipping_type,discount_applied,promo_code_used,previous_purchases,payment_method,frequency_of_purchases
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,Yes,14,Venmo,Fortnightly
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,Yes,2,Cash,Fortnightly
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,Yes,23,Credit Card,Weekly
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,Yes,49,PayPal,Weekly
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,Yes,31,PayPal,Annually

In [24]:
#create a column age group
labels = ['Young Adult', 'Adult', 'Middle-aged', 'Senior']
df['age_group'] = pd.qcut(df['age'], q=4, labels = labels)
df[['age','age_group']]

      age    age_group
0      55  Middle-aged
1      19  Young Adult
2      50  Middle-aged
3      21  Young Adult
4      45  Middle-aged
...   ...          ...
3895   40        Adult
3896   52  Middle-aged
3897   46  Middle-aged
3898   44        Adult
3899   52  Middle-aged

[3900 rows x 2 columns]

In [25]:
#create new column purchase_frequency_days

frequency_mapping = {
    'Fortnightly': 14,
    'Weekly': 7,
    'Monthly': 30,
    'Quarterly': 90,
    'Bi-Weekly': 14,
    'Annually': 365,
    'Every 3 Months': 90
}

df['purchase_frequency_days'] = df['frequency_of_purchases'].map(frequency_mapping)
df[['purchase_frequency_days','frequency_of_purchases']].head(20)

    purchase_frequency_days frequency_of_purchases
0                        14            Fortnightly
1                        14            Fortnightly
2                         7                 Weekly
3                         7                 Weekly
4                       365               Annually
5                         7                 Weekly
6                        90              Quarterly
7                         7                 Weekly
8                       365               Annually
9                        90              Quarterly
10                       14              Bi-Weekly
11                       14            Fortnightly
12                       14            Fortnightly
13                        7                 Weekly
14                        7                 Weekly
15                       30                Monthly
16                       14              Bi-Weekly
17                       90              Quarterly
18                        7                 Weekly
19                       14              Bi-Weekly

In [26]:
df[['discount_applied','promo_code_used']].head(20)

   discount_applied promo_code_used
0               Yes             Yes
1               Yes             Yes
2               Yes             Yes
3               Yes             Yes
4               Yes             Yes
5               Yes             Yes
6               Yes             Yes
7               Yes             Yes
8               Yes             Yes
9               Yes             Yes
10              Yes             Yes
11              Yes             Yes
12              Yes             Yes
13              Yes             Yes
14              Yes             Yes
15              Yes             Yes
16              Yes             Yes
17              Yes             Yes
18              Yes             Yes
19              Yes             Yes

In [27]:
(df['discount_applied'] == df['promo_code_used']).all()

np.True_

In [28]:
# Dropping promo code used column

df = df.drop('promo_code_used', axis=1)
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'previous_purchases', 'payment_method',
       'frequency_of_purchases', 'age_group', 'purchase_frequency_days'],
      dtype='object')

In [34]:
%pip install sqlalchemy pymysql pandas

Defaulting to user installation because normal site-packages is not writeable
Collecting sqlalchemy
  Using cached sqlalchemy-2.0.49-cp39-cp39-macosx_11_0_arm64.whl (2.2 MB)
Collecting pymysql
  Downloading pymysql-1.1.3-py3-none-any.whl (45 kB)
     |████████████████████████████████| 45 kB 1.2 MB/s eta 0:00:011
Requirement already satisfied: pandas in /Users/abhipsha/Library/Python/3.9/lib/python/site-packages (2.3.3)
Requirement already satisfied: typing-extensions>=4.6.0 in /Users/abhipsha/Library/Python/3.9/lib/python/site-packages (from sqlalchemy) (4.15.0)
Requirement already satisfied: tzdata>=2022.7 in /Users/abhipsha/Library/Python/3.9/lib/python/site-packages (from pandas) (2026.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/abhipsha/Library/Python/3.9/lib/python/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /Users/abhipsha/Library/Python/3.9/lib/python/site-packages (from pandas) (2026.2)
Requirement already satisfied: numpy>=1.22.4 in /Users/abhipsha/Library/Python/3.9/lib/python/site-packages (from pandas) (2.0.2)
Requirement already satisfied: six>=1.5 in /Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/site-packages (from python-dateutil>=2.8.2->pandas) (1.15.0)
Installing collected packages: sqlalchemy, pymysql
Successfully installed pymysql-1.1.3 sqlalchemy-2.0.49
WARNING: You are using pip version 21.2.4; however, version 26.0.1 is available.
You should consider upgrading via the '/Library/Developer/CommandLineTools/usr/bin/python3 -m pip install --upgrade pip' command.
Note: you may need to restart the kernel to use updated packages.

In [36]:
from sqlalchemy import create_engine
from urllib.parse import quote_plus
# MySQL connection
username = "root"
password = "Abhipsha@2002"
host = "localhost"
port = "3306"
database = "customer_behaviour"

engine = create_engine(f"mysql+pymysql://{username}:{quote_plus(password)}@{host}:{port}/{database}")

# Write DataFrame to MySQL
table_name = "customer"   # choose any table name
df.to_sql(table_name, engine, if_exists="replace", index=False)

# Read back sample
pd.read_sql("SELECT * FROM customer LIMIT 5;", engine)

,customer_id,age,gender,item_purchased,category,purchase_amount,location,size,color,season,review_rating,subscription_status,shipping_type,discount_applied,previous_purchases,payment_method,frequency_of_purchases,age_group,purchase_frequency_days
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,14,Venmo,Fortnightly,Middle-aged,14
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,2,Cash,Fortnightly,Young Adult,14
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,23,Credit Card,Weekly,Middle-aged,7
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,49,PayPal,Weekly,Young Adult,7
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,31,PayPal,Annually,Middle-aged,365

In [37]:
df.to_csv("Customer_churn.csv", index=False)

In [40]:
queries = {
    "Q1 - Revenue by Gender": """
        SELECT gender, SUM(purchase_amount) AS revenue
        FROM customer GROUP BY gender""",

    "Q2 - High Spend with Discount": """
        SELECT customer_id, purchase_amount
        FROM customer
        WHERE discount_applied = 'YES' 
        AND purchase_amount >= (SELECT AVG(purchase_amount) FROM customer)""",

    "Q3 - Average Product Rating": """
        SELECT item_purchased, ROUND(AVG(review_rating), 2) AS "Average Product Rating"
        FROM customer
        GROUP BY item_purchased
        ORDER BY AVG(review_rating) DESC LIMIT 5""",

    "Q4 - Avg Spend by Shipping Type": """
        SELECT shipping_type, ROUND(AVG(purchase_amount),2) AS avg_spend
        FROM customer
        WHERE shipping_type IN ('Standard','Express')
        GROUP BY shipping_type""",

    "Q5 - Subscription Summary": """
        SELECT subscription_status,
               COUNT(customer_id) AS total_customers,
               ROUND(AVG(purchase_amount),2) AS avg_spend,
               ROUND(SUM(purchase_amount),2) AS total_revenue
        FROM customer
        GROUP BY subscription_status
        ORDER BY total_revenue, avg_spend DESC""",

    "Q6 - Top 5 Discount Products": """
        SELECT item_purchased,
               ROUND(100.0 * SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END)/COUNT(*),2) AS discount_rate
        FROM customer
        GROUP BY item_purchased
        ORDER BY discount_rate DESC LIMIT 5""",

    "Q7 - Customer Segments": """
        WITH customer_type AS (
            SELECT customer_id,
            CASE 
                WHEN previous_purchases = 1 THEN 'New'
                WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
                ELSE 'Loyal'
            END AS customer_segment
            FROM customer
        )
        SELECT customer_segment, COUNT(*) AS total_customers
        FROM customer_type
        GROUP BY customer_segment""",

    "Q8 - Top 3 Products per Category": """
        WITH item_counts AS (
            SELECT category, item_purchased,
                   COUNT(customer_id) AS total_orders,
                   ROW_NUMBER() OVER (PARTITION BY category ORDER BY COUNT(customer_id) DESC) AS item_rank
            FROM customer
            GROUP BY category, item_purchased
        )
        SELECT item_rank, category, item_purchased, total_orders
        FROM item_counts WHERE item_rank <= 3""",

    "Q9 - Repeat Buyers by Subscription": """
        SELECT subscription_status, COUNT(customer_id) AS repeat_buyers
        FROM customer
        WHERE previous_purchases > 5
        GROUP BY subscription_status""",

    "Q10 - Revenue by Age Group": """
        SELECT 
            CASE 
                WHEN age < 26 THEN 'Young Adult'
                WHEN age BETWEEN 26 AND 45 THEN 'Middle-aged'
                WHEN age BETWEEN 46 AND 60 THEN 'Adult'
                ELSE 'Senior'
            END AS age_group,
            SUM(purchase_amount) AS total_revenue
        FROM customer
        GROUP BY 
            CASE 
                WHEN age < 26 THEN 'Young Adult'
                WHEN age BETWEEN 26 AND 45 THEN 'Middle-aged'
                WHEN age BETWEEN 46 AND 60 THEN 'Adult'
                ELSE 'Senior'
            END
        ORDER BY total_revenue DESC"""
}

for title, query in queries.items():
    print(f"\n{'='*50}\n{title}\n{'='*50}")
    display(pd.read_sql(query, engine))

==================================================
Q1 - Revenue by Gender
==================================================

   gender   revenue
0    Male  157890.0
1  Female   75191.0

==================================================
Q2 - High Spend with Discount
==================================================

     customer_id  purchase_amount
0              2               64
1              3               73
2              4               90
3              7               85
4              9               97
..           ...              ...
834         1667               64
835         1671               73
836         1673               73
837         1674               62
838         1676               90

[839 rows x 2 columns]

==================================================
Q3 - Average Product Rating
==================================================

  item_purchased  Average Product Rating
0         Gloves                    3.86
1        Sandals                    3.84
2          Boots                    3.82
3            Hat                    3.80
4          Skirt                    3.78

==================================================
Q4 - Avg Spend by Shipping Type
==================================================

  shipping_type  avg_spend
0       Express      60.48
1      Standard      58.46

==================================================
Q5 - Subscription Summary
==================================================

  subscription_status  total_customers  avg_spend  total_revenue
0                 Yes             1053      59.49        62645.0
1                  No             2847      59.87       170436.0

==================================================
Q6 - Top 5 Discount Products
==================================================

  item_purchased  discount_rate
0            Hat          50.00
1       Sneakers          49.66
2           Coat          49.07
3        Sweater          48.17
4          Pants          47.37

==================================================
Q7 - Customer Segments
==================================================

  customer_segment  total_customers
0            Loyal             3116
1        Returning              701
2              New               83

==================================================
Q8 - Top 3 Products per Category
==================================================

    item_rank     category item_purchased  total_orders
0           1  Accessories        Jewelry           171
1           2  Accessories           Belt           161
2           3  Accessories     Sunglasses           161
3           1     Clothing          Pants           171
4           2     Clothing         Blouse           171
5           3     Clothing          Shirt           169
6           1     Footwear        Sandals           160
7           2     Footwear          Shoes           150
8           3     Footwear       Sneakers           145
9           1    Outerwear         Jacket           163
10          2    Outerwear           Coat           161

==================================================
Q9 - Repeat Buyers by Subscription
==================================================

  subscription_status  repeat_buyers
0                 Yes            958
1                  No           2518

==================================================
Q10 - Revenue by Age Group
==================================================

     age_group  total_revenue
0  Middle-aged        87576.0
1        Adult        67711.0
2       Senior        43164.0
3  Young Adult        34630.0